name: 0 A.D. Mod Test

on: [push, pull_request]

jobs:
  test-mod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install 0 A.D. and Xvfb
      run: |
        sudo add-apt-repository ppa:wfg/0ad
        sudo apt-get update
        sudo apt-get install -y 0ad xvfb

    - name: Run 0 A.D. with mod using Xvfb
      run: |
        Xvfb :99 &
        export DISPLAY=:99
        0ad -mod=trojan_war -autostart="random/random" -autostart-civ="athen" -autostart-ai="petra" -autostart-ai="petra" -autostart-ais="2" -quickstart -exit-when-done
        sleep 20

    - name: Upload interesting.log
      uses: actions/upload-artifact@v2
      with:
        name: interesting-log
        path: ~/.config/0ad/logs/interesting.log
